committers:
  - name: Takeru Hayasaka
    email: t-hayasaka@bbsakura.net
  - name: Kanai Masumi
    email: m-kanai@bbsakura.net
  - name: Yuichiro RAKUNO
    email: y-rakuno@bbsakura.net
  - name: Kumakura Ryo
    email: r-kumakura@bbsakura.net
