version: "2"
run:
  build-tags:
    - vrf_test
    - xdp_test
linters:
  enable:
    - depguard
    - gocritic
    - misspell
    - predeclared
    - revive
    - unconvert
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/stretchr/testify/assert
              desc: Use github.com/stretchr/testify/require instead of github.com/stretchr/testify/assert
            - pkg: io/ioutil
              desc: Use corresponding 'os' or 'io' functions instead.
    errcheck:
      exclude-functions:
        - example/**
    revive:
      rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
        - name: unused-parameter
          severity: warning
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
      - linters:
          - staticcheck
        path: tools.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/bbsakura
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
