package gtpv2

// cf. https://github.com/wmnsk/go-gtp/blob/master/gtpv2/constants.go#L24-L65
//
//go:generate enumer -type=EnumIFType
type EnumIFType uint8

const (
	IFTypeS1UeNodeBGTPU EnumIFType = iota
	IFTypeS1USGWGTPU
	IFTypeS12RNCGTPU
	IFTypeS12SGWGTPU
	IFTypeS5S8SGWGTPU
	IFTypeS5S8PGWGTPU
	IFTypeS5S8SGWGTPC
	IFTypeS5S8PGWGTPC
	IFTypeS5S8SGWPMIPv6
	IFTypeS5S8PGWPMIPv6
	IFTypeS11MMEGTPC
	IFTypeS11S4SGWGTPC
	IFTypeS10MMEGTPC
	IFTypeS3MMEGTPC
	IFTypeS3SGSNGTPC
	IFTypeS4SGSNGTPU
	IFTypeS4SGWGTPU
	IFTypeS4SGSNGTPC
	IFTypeS16SGSNGTPC
	IFTypeeNodeBGTPUForDL
	IFTypeeNodeBGTPUForUL
	IFTypeRNCGTPUForData
	IFTypeSGSNGTPUForData
	IFTypeSGWUPFGTPUForDL
	IFTypeSmMBMSGWGTPC
	IFTypeSnMBMSGWGTPC
	IFTypeSmMMEGTPC
	IFTypeSnSGSNGTPC
	IFTypeSGWGTPUForUL
	IFTypeSnSGSNGTPU
	IFTypeS2bePDGGTPC
	IFTypeS2bUePDGGTPU
	IFTypeS2bPGWGTPC
	IFTypeS2bUPGWGTPU
	IFTypeS2aTWANGTPU
	IFTypeS2aTWANGTPC
	IFTypeS2aPGWGTPC
	IFTypeS2aPGWGTPU
	IFTypeS11MMEGTPU
	IFTypeS11SGWGTPU
)
