name: lint_and_test

on:
  push:

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
          cache-dependency-path: |
            go.sum
      - uses: jdx/mise-action@v3
      - name: add go bin to GITHUB PATH
        run: |
          echo "$(go env GOROOT)/bin" >> $GITHUB_PATH
      - name: go mod tidy
        run: go mod tidy
      - name: make install go tools
        run: make install-go-tools
      - name: pre-commit install
        run: pre-commit install
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      - name: build
        run: make build
      - name: testing
        run: make test
