name: release
on:
  push:
    branches:
      - master

permissions:
    contents: write
    pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          release-type: go
  upload-release-asset:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache-dependency-path: |
            go.sum
      - name: Run mise
        uses: jdx/mise-action@v3
      - name: Add go bin to GITHUB PATH
        run: |
          echo "$(go env GOROOT)/bin" >> $GITHUB_PATH
      - name: Make install go tools
        run: make install-go-tools
      - name: Make build
        run: make build
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./out/bin/xk6
